#lang racket
(require Racket-miniKanren/miniKanren/mk)
    
(run* (q)
     (== q 'yay))
(run 1 (q) (== 5 q))
(run 1 (q) (== 5 5))
(run 1 (q) (== 5 4))
(run 1 (q) (fresh (x y z) (== x y) (== z 3)))
(run 1 (q) (== 5 q) (== 6 q))
(run* (q) fail)
(run* (q) succeed)
(run* (q) fail (== q 3))
(define (caro p a)
  (fresh (d)
         (== (cons a d) p)))
(run* (q) (caro '(1 2) q))
(define (pluso a b c)
         (== (+ a b) c))
(run* (q) (pluso 1 2 q))
(run* (q) (pluso 1 2 3))
